Refactory Suggestions
danielsr/missao-africa-old pull request #1
Opened 2018-07-10 19:28 UTC by hugonasciutti

2018-07-11 13:23 UTC, isacjunior requested changes

2018-07-11 13:23 UTC, isacjunior commented on client/src/modules/Sponsors/SponsorsHelper.js
> +const getSponsorFromColums = cols => reduce(cols, (final, col, i) => ({ ...final, [id]: csvColumnMap[i] }), {})
`[id]`não seria `[i]`?

2018-07-11 16:28 UTC, hugonasciutti commented on client/src/modules/Sponsors/SponsorsHelper.js
> +const getSponsorFromColums = cols => reduce(csvColumnMap, (final, col, key) => ({ ...final, [key]: cols[col] }), {})
@isacjunior Corrigi para a nova versão

2018-07-12 02:19 UTC, danielsr approved these changes
Ficou ótimo, valeu demais Hugo!

2018-07-12 02:20 UTC, merged